// <auto-generated />
using System;
using CheaterWatcher.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CheaterWatcher.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904211749_AddMatchScoredAt")]
    partial class AddMatchScoredAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CheaterWatcher.Api.Domain.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("PremierRating")
                        .HasColumnType("integer");

                    b.Property<string>("Steam64Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("WingmanLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Steam64Id")
                        .IsUnique()
                        .HasFilter("\"Steam64Id\" IS NOT NULL");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("CheaterWatcher.Api.Domain.AccountMapRank", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("Map")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("AccountId", "Map");

                    b.ToTable("account_map_ranks", (string)null);
                });

            modelBuilder.Entity("CheaterWatcher.Api.Domain.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CtScore")
                        .HasColumnType("integer");

                    b.Property<bool>("DeleteDemoAfterParse")
                        .HasColumnType("boolean");

                    b.Property<string>("DemoFileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("DemoSourceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FlaggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("OurTeamNumber")
                        .HasColumnType("integer");

                    b.Property<short?>("OwnRankType")
                        .HasColumnType("smallint");

                    b.Property<int?>("OwnRankValue")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ParsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ScoredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("Suspected")
                        .HasColumnType("boolean");

                    b.Property<int>("TScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FinishedAt");

                    b.HasIndex("AccountId", "DemoSourceId")
                        .IsUnique()
                        .HasFilter("\"DemoSourceId\" IS NOT NULL");

                    b.HasIndex("AccountId", "Status");

                    b.HasIndex("AccountId", "Mode", "FinishedAt");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("CheaterWatcher.Api.Domain.MatchPlayer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<string>("FlagNote")
                        .HasColumnType("text");

                    b.Property<int>("FlagReason")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FlaggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<short?>("RankType")
                        .HasColumnType("smallint");

                    b.Property<int?>("RankValue")
                        .HasColumnType("integer");

                    b.Property<string>("Steam64Id")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SuspicionBreakdownJson")
                        .HasColumnType("jsonb");

                    b.Property<double?>("SuspicionScore")
                        .HasColumnType("double precision");

                    b.Property<int>("TeamNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Steam64Id");

                    b.HasIndex("MatchId", "Steam64Id");

                    b.ToTable("match_players", (string)null);
                });

            modelBuilder.Entity("CheaterWatcher.Api.Domain.PendingReplay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastWriteTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PlayerNamesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PlayerSteamIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<int?>("ResolvedAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FileHash");

                    b.HasIndex("ResolvedAccountId");

                    b.HasIndex("Status");

                    b.ToTable("pending_replays", (string)null);
                });

            modelBuilder.Entity("CheaterWatcher.Api.Domain.PlayerStatsCache", b =>
                {
                    b.Property<string>("Steam64Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Steam64Id");

                    b.ToTable("player_stats_cache", (string)null);
                });

            modelBuilder.Entity("CheaterWatcher.Api.Domain.ProcessedReplay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastWriteTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.HasKey("Id");

                    b.HasIndex("FileHash")
                        .IsUnique();

                    b.ToTable("processed_replays", (string)null);
                });

            modelBuilder.Entity("CheaterWatcher.Api.Domain.ReplayScanSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HostPath")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<DateTime?>("LastScanAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastScanAttributed")
                        .HasColumnType("integer");

                    b.Property<string>("LastScanError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("LastScanNew")
                        .HasColumnType("integer");

                    b.Property<int>("LastScanPending")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("replay_scan_settings", (string)null);
                });

            modelBuilder.Entity("CheaterWatcher.Api.Domain.AccountMapRank", b =>
                {
                    b.HasOne("CheaterWatcher.Api.Domain.Account", "Account")
                        .WithMany("MapRanks")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CheaterWatcher.Api.Domain.Match", b =>
                {
                    b.HasOne("CheaterWatcher.Api.Domain.Account", "Account")
                        .WithMany("Matches")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CheaterWatcher.Api.Domain.MatchPlayer", b =>
                {
                    b.HasOne("CheaterWatcher.Api.Domain.Match", "Match")
                        .WithMany("Players")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("CheaterWatcher.Api.Domain.PendingReplay", b =>
                {
                    b.HasOne("CheaterWatcher.Api.Domain.Account", "ResolvedAccount")
                        .WithMany()
                        .HasForeignKey("ResolvedAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ResolvedAccount");
                });

            modelBuilder.Entity("CheaterWatcher.Api.Domain.Account", b =>
                {
                    b.Navigation("MapRanks");

                    b.Navigation("Matches");
                });

            modelBuilder.Entity("CheaterWatcher.Api.Domain.Match", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
